// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPiKd0Z0xYQJRGAVBsAK5cfY14PC4SU7w',
    appId: '1:1061329638408:web:1ebbba682119364a55adbd',
    messagingSenderId: '1061329638408',
    projectId: 'fun88-project',
    authDomain: 'fun88-project.firebaseapp.com',
    storageBucket: 'fun88-project.firebasestorage.app',
    measurementId: 'G-Y1WXHJFS2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeZKj2_oa68_kf-IQRjBdHIxF0kFixHcU',
    appId: '1:1061329638408:android:dd668bba59ab311055adbd',
    messagingSenderId: '1061329638408',
    projectId: 'fun88-project',
    storageBucket: 'fun88-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKoZoza24_6gKAs3wX1MChlyKNYNT1TOQ',
    appId: '1:1061329638408:ios:bcb99583d71856a055adbd',
    messagingSenderId: '1061329638408',
    projectId: 'fun88-project',
    storageBucket: 'fun88-project.firebasestorage.app',
    iosBundleId: 'com.example.fun88Clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKoZoza24_6gKAs3wX1MChlyKNYNT1TOQ',
    appId: '1:1061329638408:ios:bcb99583d71856a055adbd',
    messagingSenderId: '1061329638408',
    projectId: 'fun88-project',
    storageBucket: 'fun88-project.firebasestorage.app',
    iosBundleId: 'com.example.fun88Clone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPiKd0Z0xYQJRGAVBsAK5cfY14PC4SU7w',
    appId: '1:1061329638408:web:03801210ac88b11d55adbd',
    messagingSenderId: '1061329638408',
    projectId: 'fun88-project',
    authDomain: 'fun88-project.firebaseapp.com',
    storageBucket: 'fun88-project.firebasestorage.app',
    measurementId: 'G-N92RDKSLYQ',
  );
}
